dist:     trusty
sudo:     required

language: cpp

os:
  - linux

compiler:
  - g++

addons:
  apt:
    packages: lcov

install:
  - source ci/travis/install-linux.sh

script:
  - cd iz_1
  - cmake -DCMAKE_BUILD_TYPE=Test ./
  - make
  - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./iz_1
