#ifndef IZ_1_CONSTANTS_H
#define IZ_1_CONSTANTS_H

#define DEFAULT_ALLOCATED_SIZE 4
#define MAX_BANK_NAME_LEN 10
#define CURRENCY_NAME_LEN 4
#define EPS 1e-6
#define FALSE 0

#endif //IZ_1_CONSTANTS_H
